### ISSUE TITLE
FR: can the command be `sad` insted of `Sad` ?

### ISSUE THREAD

**Issue by marcelmanz** [ray-x/sad.nvim#1]
i just hate Capital letters

**Comment by ray-x** [comment]
I do not think the self-defined command can be lower cased. Correct me if I am wrong.

**Comment by marcelmanz** [comment]
yep that's right. I didn't know ¯\_(ツ)_/¯ 

I found this that it's enough for me
`:cabbrev sed Sed`

Thanks!!
