### ISSUE TITLE
Select all by default

### ISSUE THREAD

**Issue by louwers** [ray-x/sad.nvim#13]
I would like to select all by default.

Maybe the third argument of `'sad'.replace` can be made to accept a table with options?

**Comment by ray-x** [comment]
well, there are no options/flags to pass to `sad` cli to select all by default. Beyond scope ATM

**Comment by ray-x** [comment]
@louwers 
Although the plugin does not provide a way to select everything by default, but there is a keybinding
`<ctrl-a>` which selects and unselects all items. Does it work for you
