### ISSUE TITLE
Is multiline and regex grouping supported?

### ISSUE THREAD

**Issue by budimanjojo** [ray-x/sad.nvim#14]
Hello, I can't seem to make this example from the official `sad` documentation work: `Replace all'"(\d+)"' -> '🌈$1🌈' in the chromium repo.` The result will simply ignore the `$1` and just replace them the 2 rainbows.

I also can't get multiline regex to work, something like replacing a `yaml` file e.g `Sad '"(firstKey: firstValue\n\s+secondKey: )"secondValue' '$1newSecondValue'`. 

Thanks for the nice plugin!

**Comment by ray-x** [comment]
Ok, I added extra escape to `\n` and `$` so it did not work for some of the shells
I removed the escape and hope it works for you now.

**Comment by budimanjojo** [comment]
@ray-x Thanks! It works! However, on multiline there's an issue where the replacement doesn't work when I put it like this: `$1newSecondValue` but it works with `$1:\ newSecondValue` like the example in your commit.

**Comment by ray-x** [comment]
In that case, you can use this:
'${1}newSecondValue'
```vim
Sad (firstKey:firstValue\n\s*secondKey:) ${1}newSecondValue
```
