### ISSUE TITLE
Two typos in README

### ISSUE THREAD

**Issue by ReekenX** [ray-x/sad.nvim#15]
I am experimenting with your plugin and noticed two typos in your README.

1) Missing comma in `Configure` section right after `debug`:

![CleanShot 2023-02-20 at 17 04 08@2x](https://user-images.githubusercontent.com/242010/220141563-75266e1a-6e2e-4b58-869d-c996ac52bf31.png)

2) Not `git ls_file` but `git ls-files`:

![CleanShot 2023-02-20 at 17 04 36@2x](https://user-images.githubusercontent.com/242010/220141657-e937fd0d-90f3-44d0-b39c-5be9d9473730.png)

**Comment by ray-x** [comment]
Thanks, should been fixed
