### ISSUE TITLE
Error on apply: "attempt to call field 'log' (a nil value)"

### ISSUE THREAD

**Issue by ranelpadon** [ray-x/sad.nvim#3]
After confirming the changes, there's an error:
<img width="452" alt="Screen Shot 2021-12-18 at 8 02 13 AM" src="https://user-images.githubusercontent.com/4292088/146621024-e8983b96-1ba0-4bef-94a5-10739cca0bd3.png">

Apparently, fails on this part. Maybe it couldn't reference `log()` correctly?
https://github.com/ray-x/guihua.lua/blob/master/lua/guihua/floating.lua#L245

I commented that line on my local as workaround for now. BTW, thanks for this interesting plugin. :)

**Comment by ray-x** [comment]
Thanks for submit the issue. I commit a fix to guihua.lua and hope it works.

**Comment by ranelpadon** [comment]
This is confirmed working, or at least no more error. Thanks will close the issue now. :)
