### ISSUE TITLE
How to apply ALL items

### ISSUE THREAD

**Issue by ranelpadon** [ray-x/sad.nvim#4]
The `README` has this:
> <CR> to confirm and apply all the replacements

But `<CR>`/`ENTER` seems to have no effect. It will only confirm the first item which is the default item:

<img width="703" alt="Screen Shot 2021-12-18 at 8 10 13 AM" src="https://user-images.githubusercontent.com/4292088/146622508-c2746b8c-1e41-4783-9e57-7af83e436048.png">

The [sad](https://github.com/ms-jpq/sad) CLI has `--commit` option which auto-confirms all. And I could use this `FZF` option to bind the `Ctrl-A` to select all:
```bash
export FZF_DEFAULT_OPTS="-m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all"
```

 `Ctrl-A` works in `sad` CLI (as indicated by **>** in all lines):

<img width="1434" alt="Screen Shot 2021-12-18 at 8 30 43 AM" src="https://user-images.githubusercontent.com/4292088/146622413-53c2891c-1817-42c6-b825-f08c631b725a.png">

Also, `Ctrl-A` works in `FZF.vim` (with `Rg`):

<img width="1437" alt="Screen Shot 2021-12-18 at 8 25 36 AM" src="https://user-images.githubusercontent.com/4292088/146622451-0874ea5b-c964-462c-b025-c8175088d9ae.png">

But `Ctrl-A` doesn't work in `sad.nvim`. Am I missing something?

BTW, thanks for this interesting plugin. :)

**Comment by ray-x** [comment]
Thanks for the suggestion. I added <C-A> keybinding

**Comment by ranelpadon** [comment]
This is confirmed working. Thanks also for your prompt feedback. :)
