### ISSUE TITLE
Increase the Sad window

### ISSUE THREAD

**Issue by ranelpadon** [ray-x/sad.nvim#5]
Is it possible to increase the `Sad` window, like via config option? Since it's too narrow in most cases, and the line is being cut and displayed in new line, hence not good UX:

<img width="1436" alt="Screen Shot 2022-02-20 at 3 06 07 AM" src="https://user-images.githubusercontent.com/4292088/154815348-d3b14e54-a0df-49cd-b315-d19ecfd4e6d4.png">

Ideally, it could occupy 80-100% of the screen. The user doesn't care much about the file explorer/editor window anyway while using `Sad`, so might as well maximize the screen estate, especially if it's in the floating terminal. Just like in the `sad` CLI which is in full-screen mode. Thanks!

**Comment by ray-x** [comment]
You should do this with the latest version:
```
    require("sad").setup({ vsplit = false, height_ratio = 0.9 })

```

**Comment by ranelpadon** [comment]
@ray-x Thanks for your prompt reply. I pulled the latest codes, but it seems to have no effect. Tried:
- updating my `init.vim`:
`lua require("sad").setup({ vsplit = false, height_ratio = 0.9 })`
- hardcoding the values:
    ```lua

    local term = function(opts)
        opts.term_name = term_name
        _SAD_CFG = _SAD_CFG or {} -- supress luacheck warning

        opts.vsplit = false
        opts.height_ratio = 0.9  -- tried 0.2 also and other values
        opts.width_ratio = 0.9  -- tried 0.2 also and other values
       return guihua_term.gui_term(opts)
    end
    ```
- removing the config/values:
    ```lua
    local term = function(opts)
        opts.term_name = term_name
        _SAD_CFG = _SAD_CFG or {} -- supress luacheck warning

        return guihua_term.gui_term(opts)
    end
    ```

But the window still looks the same, as per my screenshot above. Am I missing something? Or could there be other factors or requirements? I'm using Neovim **0.6.1** stable, and no errors thrown also.

**Comment by ray-x** [comment]
Did you updated `guihua.lua` ?

**Comment by ranelpadon** [comment]
@ray-x You're right, need to update that `guihua.lua` plugin also. And now the size could be varied indeed:

<img width="1437" alt="Screen Shot 2022-02-20 at 1 13 18 PM" src="https://user-images.githubusercontent.com/4292088/154829467-f0d3f927-9c3b-4bb9-b3cc-a35ab77afaad.png">

Thanks a lot! :)
