### ISSUE TITLE
Is it possible to open preview with telescope rathen than fzf?

### ISSUE THREAD

**Issue by jugarpeupv** [ray-x/sad.nvim#8]
I would like to open it with telescope since i have already configured result window width etc

**Comment by ray-x** [comment]
Sorry, it is not ATM. As the preview and filter heavily depend on FZF.

**Comment by louwers** [comment]
Telescope also does not support multi select.

**Comment by aniketgm** [comment]
> Telescope also does not support multi select.

@louwers Yes it does, check out `actions.toggle_selection` in telescope help.
Check out this thread too, might be helpful: https://github.com/nvim-telescope/telescope.nvim/issues/416

**Comment by ray-x** [comment]
You can multi-select with telescope and then send to quickfix.
After that, use `cfdo` to replace.
Well, I used to do that very often before using sad.
