### ISSUE TITLE
Diff view takes up less space than available

### ISSUE THREAD

**Issue by sbmueller** [ray-x/sad.nvim#9]
Using `delta`, the diff view is much smaller than the real estate provided:
![sad](https://user-images.githubusercontent.com/7465688/198283738-39303f83-ae8d-4cff-bca7-a81c639589dc.png)

Using the default config from the README.

**Comment by ray-x** [comment]
It is kind of a known issue of using delta. Similar issue also existed in fzf. May need to check how fzf.nvim address this.

**Comment by ray-x** [comment]
Should be fixed
![image](https://user-images.githubusercontent.com/1681295/210460515-55935f1e-1a8b-4c91-9fe7-20d7365f93f6.png)
